### ISSUE TITLE
Automate chart version bumping

### ISSUE THREAD

**Issue by hairmare** [adfinis-sygroup/helm-charts#218]
**Is your feature request related to a problem? Please describe.**
Keeping Chart versions bumped when implementing features and preparing PRs for rollout can be cumbersome and a tad frustrating. 

**Describe the solution you'd like**
A GitHub Action that takes care of keeping the versions how they should be for us.
* It should parse semantic-commit messages and use them to decide what to bump
* It should support 0.x versions
* it should only bump versions as/where needed

**Describe alternatives you've considered**
We continue bumping manually and maybe start using tools like [helm-local-chart-version](https://github.com/mbenabda/helm-local-chart-version) as part of our local workflow.

**Affected chart**
none, CI

**Additional context**
This might save some time in those moments where a lot of bumps are ready for a given chart. This could also be the foundation for more automation like update PRs at a later stage.

**Comment by hairmare** [comment]
all my unpublished proof of concepting for this has been following the "write some code to do it" approach and i still have nothing to show that resembles a solution that is maintainable.

[this post](https://github.com/dependabot/dependabot-core/issues/2237#issuecomment-1175839217) highlighted the idea of using an existing tool rather than having to write our own. The linked [updatecli](https://github.com/updatecli/updatecli) look like something we'd want to investigate closely.

**Comment by olblak** [comment]
Hi here, 

I accidentally found your discussion.
I hope you don't mind me jumping here.

I am the creator of Updatecli

First of all thank you for considering Updatecli.

Your use case is interesting. @dduportal has been pushing in the same direction than you
I just want to add that if you use the GitHub flow, then you could have two commits but one pullrequest.
That's what we do all the time, you need the following snippet in your manifest.

```
pullrequests:
  helm-charts:
    kind: github
    scmid: helm-charts
    spec:
      automerge: false
      labels:
        - dependencies
```

Another thing that appears to be confusing here is the difference between the scm of kind `git` and `github`.
the git scm would commit directly to the branch specified in your manifest while the "github" one create a temporary branch and is designed to be used with a pullrequest, so it open a pullrqeuest from that temporary branch to the one specified in the manifest.

So the github scm implements the GitHub flow, I got many feedback that it's not an intuitive behavior. 
We had lengthy discussion about how this behavior should evolved, and I also have an open pullrequest but we never finished that discussion...

Meanwhile I have been focusing on another area.

To reduce the need to write and maintain manifest, I worked on a feature named "autodiscovery" where Updatecli would detected common behavior. It's still experimental as I am still playing with it to identify the best way to use it. And I would love some feedback

You can have taste with the latest version of Updatecli.
The following manifest should be enough to start with.

By the way manifests under the directory named "updatecli.d" are recognized by IDE(s) that support jsonschema store (like vscode), so you get validation, and autocompletion for free.

updatecli.d/autodiscovery.yaml
```
name: Update app of apps charts

scms:
  helm-charts:
    kind: "github"
    spec:
      branch: "main"
      user: "adfinisbot"
      email: "support@adfinis.com"
      owner: "hairmare"
      repository: "adfinis-helm-charts"
      token: '{{ requiredEnv "GITHUB_TOKEN" }}'
      username: '{{ requiredEnv "GITHUB_ACTOR" }}'

pullrequests:
  helm-charts:
    kind: github
    scmid: helm-charts
    spec:
      automerge: false
      labels:
        - dependencies

autodiscovery:
  # scmid is applied to all crawlers
  scmid: helm-charts
  crawlers:
    helm:
      # To ignore specific path
      #ignore:
      #  # - path: <filepath relative to scm repository>
      #  # - path: chart/*
      #only:
      #  # - path: <filepath relative to scm repository>
      #  # - path: chart/*
```

Then run `updatecli diff --experimental --config updatecli.d/autodiscovery.yaml`

To see what would have to change.

I still believe that we need to execute more custom pipeline in parallel, hence the reason to allow to opt out using the ignore/only configuration. But it's not yet clear how much configuration I need from the autodiscovery versus writing the source/condition/target manifest
