### ISSUE TITLE
manage appprojects in `*-app`

### ISSUE THREAD

**Issue by hairmare** [adfinis-sygroup/helm-charts#685]

**Comment by hairmare** [comment]
Current solution is to use `misc-apps`:

```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: misc-apps
  namespace: infra-argocd
spec:
  destination:
    namespace: infra-argocd
    server: https://kubernetes.default.svc
  project: infra-argocd
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  source:
    chart: misc-apps
    repoURL: https://charts.adfinis.com
    targetRevision: "*"
    helm:
      values: |
        fullnameOverride: app
        argocdApps:
          enabled: true
          project: infra-argocd
          syncPolicy:
            automated: {}
            syncOptions:
              - CreateNamespace=true
          destination:
            server: https://kubernetes.default.svc
            namespace: infra-argocd
          values:
            projects: []
```
I still think this issue should be something to consider tho.
